"""nutrition_phase1_new_tables_and_pet_fields

Revision ID: 5cbc1aaf70f2
Revises: c2ae1a9a1d4f
Create Date: 2026-04-25 21:22:52.472483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5cbc1aaf70f2'
down_revision: Union[str, None] = 'c2ae1a9a1d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS food_categories (
            id SERIAL NOT NULL,
            name VARCHAR(100) NOT NULL,
            food_type VARCHAR(50) NOT NULL,
            kcal_per_100g NUMERIC(6,2) NOT NULL,
            protein_pct NUMERIC(5,2) NOT NULL,
            fat_pct NUMERIC(5,2) NOT NULL,
            fiber_pct NUMERIC(5,2) NOT NULL,
            notes TEXT,
            PRIMARY KEY (id)
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS breed_risks (
            id SERIAL NOT NULL,
            breed_name VARCHAR(100) NOT NULL,
            risk_key VARCHAR(50) NOT NULL,
            PRIMARY KEY (id)
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS stop_foods (
            id SERIAL NOT NULL,
            species VARCHAR(50) NOT NULL,
            level INTEGER NOT NULL,
            product_name VARCHAR(200) NOT NULL,
            toxic_component TEXT,
            clinical_effect TEXT,
            source VARCHAR(200),
            PRIMARY KEY (id)
        )
    """)
    op.execute("ALTER TABLE pets ADD COLUMN IF NOT EXISTS is_neutered BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE pets ADD COLUMN IF NOT EXISTS activity_level VARCHAR(50) NOT NULL DEFAULT 'moderate'")
    op.execute("ALTER TABLE pets ADD COLUMN IF NOT EXISTS physio_status VARCHAR(50) NOT NULL DEFAULT 'normal'")
    op.execute("ALTER TABLE pets ADD COLUMN IF NOT EXISTS food_category_id INTEGER REFERENCES food_categories(id)")
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_name = 'fk_pets_food_category'
            ) THEN
                ALTER TABLE pets ADD CONSTRAINT fk_pets_food_category
                FOREIGN KEY (food_category_id) REFERENCES food_categories(id);
            END IF;
        END $$
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pets_food_category', 'pets', type_='foreignkey')
    op.drop_column('pets', 'food_category_id')
    op.drop_column('pets', 'physio_status')
    op.drop_column('pets', 'activity_level')
    op.drop_column('pets', 'is_neutered')
    op.drop_table('stop_foods')
    op.drop_table('food_categories')
    op.drop_table('breed_risks')
    # ### end Alembic commands ###
