"""nutrition_phase1_new_tables_and_pet_fields

Revision ID: 5cbc1aaf70f2
Revises: c2ae1a9a1d4f
Create Date: 2026-04-25 21:22:52.472483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5cbc1aaf70f2'
down_revision: Union[str, None] = 'c2ae1a9a1d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breed_name', sa.String(length=100), nullable=False),
    sa.Column('risk_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('food_type', sa.String(length=50), nullable=False),
    sa.Column('kcal_per_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fat_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fiber_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stop_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('toxic_component', sa.Text(), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pets', sa.Column('is_neutered', sa.Boolean(), nullable=False))
    op.add_column('pets', sa.Column('activity_level', sa.String(length=50), nullable=False))
    op.add_column('pets', sa.Column('physio_status', sa.String(length=50), nullable=False))
    op.add_column('pets', sa.Column('food_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_pets_food_category', 'pets', 'food_categories', ['food_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pets_food_category', 'pets', type_='foreignkey')
    op.drop_column('pets', 'food_category_id')
    op.drop_column('pets', 'physio_status')
    op.drop_column('pets', 'activity_level')
    op.drop_column('pets', 'is_neutered')
    op.drop_table('stop_foods')
    op.drop_table('food_categories')
    op.drop_table('breed_risks')
    # ### end Alembic commands ###
