"""add_nutrition_reminders

Revision ID: b058cf0c0fa2
Revises: 29ee4ae16f0f
Create Date: 2026-04-18 18:00:14.189354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b058cf0c0fa2'
down_revision: Union[str, None] = '29ee4ae16f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('rer_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('kcal_per_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stop_foods', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeding_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('daily_calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('daily_food_grams', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('food_per_meal_grams', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rations')
    op.drop_table('feeding_reminders')
    op.drop_table('nutrition_knowledge')
    # ### end Alembic commands ###
